### ISSUE TITLE
Nav a tags need to be block level elements

### ISSUE THREAD

**Issue by germangamboa95** [BennyCarlsson/MyPortfolio-Hacktoberfest2019#108]
Right now the links are inline and only respond to being click directly on them. We should make them block level elements to fix this.

**Comment by BhathiyaTK** [comment]
Hey @germangamboa95! Can I take this?

**Comment by lordkerwin** [comment]
Hey, can I have a go at this?

**Comment by germangamboa95** [comment]
No need to ask, just do it :D

**Comment by echowebid** [comment]
Please review #142

**Comment by BennyCarlsson** [comment]
Great work!
