### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by BennyCarlsson** [BennyCarlsson/MyPortfolio-Hacktoberfest2019#183]
Change or add design on the website 🍪

**Comment by iamshm** [comment]
Can you specify what exactly do you want?

**Comment by BennyCarlsson** [comment]
@iamshm I don't have any specific in mind. You can change or add almost anything ;)

**Comment by iamshm** [comment]
cool then I'll try to enhance this website :)

**Comment by iamshm** [comment]
I did enhance a bit. I'm a new webdev so I did my best.

**Comment by BennyCarlsson** [comment]
Great work thanks :)

**Comment by thecodeah** [comment]
Challenge accepted :thinking:

**Comment by BennyCarlsson** [comment]
Awesome work will close this for now
