### ISSUE TITLE
Javascript cleanup

### ISSUE THREAD

**Issue by BennyCarlsson** [BennyCarlsson/MyPortfolio-Hacktoberfest2019#191]
A lot of easter eggs and javascript is broken.

**Comment by blacksag** [comment]
The `app.js` is completely broken and there are too many easter eggs to handle. I would like to work on this and make it simpler by removing some of the easter eggs.

**Comment by BennyCarlsson** [comment]
@blacksag go ahead! closing this for now but feel free to continue on it
