### ISSUE TITLE
CSS Cleanup

### ISSUE THREAD

**Issue by BennyCarlsson** [BennyCarlsson/MyPortfolio-Hacktoberfest2019#226]
I belive a lot of the CSS can be cleaned up

**Comment by shahkv95** [comment]
Would like to start from improving the navbar!
Can I take this task and contribute for the same? @BennyCarlsson

**Comment by BennyCarlsson** [comment]
@shahkv95 everything is free for all so go ahead :)

**Comment by mrpbennett** [comment]
I'm going to take this on also, ill create a branch in my name

**Comment by beatrizsmerino** [comment]
Hi!! I would like refactoring the code css, responsive, something of html.
I created a branch with my name  (beatrizsmerino).
This it is my first pull request.

**Comment by BennyCarlsson** [comment]
@beatrizsmerino Saw your pull request and left a comment. You can fix the merge conflict if you have time and I'll happilly merge. Closing the issue for now so no one else starts working on it
