### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by BennyCarlsson** [BennyCarlsson/MyPortfolio-Hacktoberfest2019#233]
Change, update or edit the text / content on the website

**Comment by Johan-Ng** [comment]
Index.html? Can I take part in this? What content/ text would you want?

**Comment by MouadBH** [comment]
More info

**Comment by franky1234** [comment]
More info...Please. 
Size, Height of the text, font-size, font-style.. etc..or just the meaning of the content?
Same question on design.

**Comment by zebemce** [comment]
Thanks for interest. Web GUI is intended to be source editor and status monitoring tool. Perhaps it can be just some readme first.

**Comment by oswaldo100** [comment]
repit apliqueshon devilodermen

**Comment by olegbez007** [comment]
I need note[ad c++ commadns in php scripts with simple notepad to send send commands for all myu sites for all 20000 pages that thety should be cleaned and minifyed. :))
^[ \t]*$\r?\n

Ijust need mass compressor for php, css, js. Compress like heere https://htmlcompressor.com/compressor/  BUT not by 1 page. Buy 1000 at least. Notepad windosw and notebook are dying whis such reguest :)

**Comment by oswaldo100** [comment]
vivo lejos calzo grande

**Comment by SparshKat** [comment]
May i take this up? As no information regarding the style of font is giveen.hence i will make changes that would look good according to me....please review it once :)
