### ISSUE TITLE
laravel routes conflict

### ISSUE THREAD

**Issue by lejober95** [BennyCarlsson/MyPortfolio-Hacktoberfest2019#274]
I try to set up route localhost:8000/vers or localhost:8000/register in laravel using following routes:
![route](https://user-images.githubusercontent.com/53325783/67262561-cc36ee80-f494-11e9-88ef-fdad8a3ee434.JPG)
but when i go to  localhost:8000/vers or localhost:8000/register it runs the  localhost:8000/test
or the localhost /voir_doc/{voirmat} . please help , i get troubled

==> je ne cesse de me troubler, S'il vous plait aidez moi,  quand j'essaie de lancer <<localhost:8000/vers ou localhost:8000/register>> ce sont les routes << localhost:8000/test  ou localhost:8000>> qui répondent en lieu et place en tout cas les routes <<vers  et  register>> ne répondent pas

**Comment by lejober95** [comment]
Please I need help

**Comment by vxzry** [comment]
hi, this is caused by the order of your routes; Laravel goes through the routes from top to bottom.

Placing the `Route::get('/test?', 'EtudController@test');` on top which has an optional parameter `test?`, makes your other routes (`/vers` and `/register`) unreachable. 

Any entries after the `/` is assumed as the parameter for your `Route::get('/test?', 'EtudController@test');`  route

You could try rearranging your routes.

**Comment by lejober95** [comment]
Hi thank you 
but explain me a little bit this way  to do

**makes your other routes (/vers and /register) unreachable.** how? by deleting the "/" ?

**Comment by lejober95** [comment]
> hi, this is caused by the order of your routes; Laravel goes through the routes from top to bottom.
> 
> Placing the `Route::get('/test?', 'EtudController@test');` on top which has an optional parameter `test?`, makes your other routes (`/vers` and `/register`) unreachable.
> 
> Any entries after the `/` is assumed as the parameter for your `Route::get('/test?', 'EtudController@test');` route
> 
> You could try rearranging your routes.

Hi thank you
but explain me a little bit this way to do

makes your other routes (/vers and /register) unreachable. how? by deleting the "/" ?

**Comment by vxzry** [comment]
It takes the words "vers" and "register" as an input for your test parameter. You could try printing the request from the test method on your controller to see if it will print those words.
