### ISSUE TITLE
Double github icons

### ISSUE THREAD

**Issue by BennyCarlsson** [BennyCarlsson/MyPortfolio-Hacktoberfest2019#296]
In the right corner there are 2 github icons/links. Should only be 1 the second one probably got there because of a bad merge 😄

**Comment by bhadreshpsavani** [comment]
I could not find two GitHub icons, Could you please tell me where exactly the two icons appear. I can help with this.

**Comment by 22PoojaGaur** [comment]
created pull request for this #298

**Comment by shakti97** [comment]
Sorry guyz but let me tell you one thing or you can say the first rule of OSS is first comment in the issue that you started working on it or just ask can i work on this then only proceed , it's a indication that someone already working on this which will saves other developer's time

**Comment by evergreen2001** [comment]
can i take this one

**Comment by shakti97** [comment]
Sorry @evergreen2001 but there are already 2 PR

**Comment by BennyCarlsson** [comment]
this got fixed however now it's completetly gone :S If anyone have time they can add it back :) closing this for now
