### ISSUE TITLE
HTML cleanup

### ISSUE THREAD

**Issue by BennyCarlsson** [BennyCarlsson/MyPortfolio-Hacktoberfest2019#305]
I think there is a lot of html that is not used and can be cleaned up

**Comment by neckenth** [comment]
I can take this on :) Can I be assigned?

**Comment by BennyCarlsson** [comment]
Hi @neckenth  most issues are free for all so you can just start on it :) it's a really messy project :)

**Comment by neckenth** [comment]
Gotcha will do :)
