### ISSUE TITLE
Left sidebar dublicate

### ISSUE THREAD

**Issue by BennyCarlsson** [BennyCarlsson/MyPortfolio-Hacktoberfest2019#315]
Looks like a bad merge have made the left sidebar dublicated. So now the pikachu gif and stuff covers some content.

**Comment by CapitanFindusFI** [comment]
I think I'll have a go on this

**Comment by smsriharsha** [comment]
done in pull request #316

**Comment by BennyCarlsson** [comment]
This is done great work!
