### ISSUE TITLE
Font-awesome is behing loaded twice

### ISSUE THREAD

**Issue by marcelosantos89** [BennyCarlsson/MyPortfolio-Hacktoberfest2019#45]
Someone could fix this

`<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">`

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css">`

**Comment by BennyCarlsson** [comment]
Great Work!
