### ISSUE TITLE
More features

### ISSUE THREAD

**Issue by BennyCarlsson** [BennyCarlsson/MyPortfolio-Hacktoberfest2019#49]
The website needs some buttons and features maybe some easter eggs

**Comment by SidneyMachara** [comment]
hi , i'd like to do this , please assign it to me

**Comment by BennyCarlsson** [comment]
@SidneyMachara no need for assignment you can just do a pull request :)

**Comment by moisesjsanchez** [comment]
Hello, are there any ideas you had in mind in terms of easter eggs?

**Comment by BennyCarlsson** [comment]
@moisesjsanchez anything works :) from simple console.logs to spinning websites

**Comment by chrysillala** [comment]
hey, may i help you? any specific ideas on this issue?
