### ISSUE TITLE
Profile picture image broken

### ISSUE THREAD

**Issue by BennyCarlsson** [BennyCarlsson/MyPortfolio-Hacktoberfest2019#55]
the link to the profile picture is broken

**Comment by JoshHeng** [comment]
There is no logo file:
`<img src="#" alt="logo" />` 

Do you have one you want to use?

**Comment by srbilla** [comment]
#69 fixed

**Comment by BennyCarlsson** [comment]
@JoshHeng we got one now but if you have a better one feel free to change it :)  I don't have a preference ;)

**Comment by BennyCarlsson** [comment]
closing it for now but feel free to change the image
