### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by BennyCarlsson** [BennyCarlsson/MyPortfolio-Hacktoberfest2019#6]
Some links to my twitter, linkedin, youtube and github would be nice

https://twitter.com/Benny_Carlsson
https://www.linkedin.com/in/benny-carlsson-620226ba/
https://www.youtube.com/channel/UCpPEhf3aRau_Tgzbk91YZLg
https://github.com/BennyCarlsson

**Comment by Sweta271097** [comment]
@BennyCarlsson Can I take up this issue?

**Comment by BennyCarlsson** [comment]
Great Work !
