### ISSUE TITLE
left sidebar is pushed down

### ISSUE THREAD

**Issue by BennyCarlsson** [BennyCarlsson/MyPortfolio-Hacktoberfest2019#92]
Something is pushing down the left sidebar (profile picture, Benny Carlsson, Software Developer, links)

So the links is not shown

**Comment by ayushman2001** [comment]
i want to work on this

**Comment by BennyCarlsson** [comment]
@ayushman2001 go ahead everything is free for all :)

**Comment by 20Koen02** [comment]
#97 also fixed the profile being too far to the right

**Comment by BhathiyaTK** [comment]
Hello @BennyCarlsson! Fixed left sidebar issue: #100

**Comment by BennyCarlsson** [comment]
Great Work 👍
